Version 0.2.0 proposal
CrystalGamesMC/Scaffolding pull request #11
Opened 2022-05-17 22:23 UTC by DamianKocher

This PR fixes many issues but probably creates many more. I believe these changes are necessary to reach a point where this library can be used in a production capacity. 

**Fixes**
Fixes #4 - Scaffolding methods now cannot return null
Fixes #8 - Schematics now cannot be placed in positions which would put them outside of world bounds
Fixes #10 - MCEdit schematics now use correct block palette 

**Improvements**
- More documentation
- Distribution via JitPack is supported
- Use CompletableFutures wherever possible
- Rewrite schematic loading to make adding new schematic formats easier
- WIP wiki site
- WIP WorldEdit like editor server
- Many other small changes

2022-05-17 22:27 UTC, SLLCoding commented
you madman

2022-05-17 22:40 UTC, DamianKocher commented
> you madman

yeah i might've gotten a bit carried away lmao

2022-05-18 19:06 UTC, SLLCoding requested changes
Formatting is a bit odd with the lack of spaces at the end of files, other than that and a few other comments, looking really good and quite interesting.

Was actually planning to migrate to Gradle, thank goodness someone did it for me.

2022-05-18 19:06 UTC, LooFifteen commented on .gitignore
> +# *.ipr
This stuff should be uncommented.

2022-05-18 19:06 UTC, LooFifteen commented on .gitignore
> +.idea/
hmmmm

2022-05-18 19:06 UTC, LooFifteen commented on scaffolding-core/build.gradle.kts
> +    testImplementation("me.alexpanov:free-port-finder:1.1.1")
Should probably just use port 25565 for convenience sake.

2022-05-18 19:06 UTC, LooFifteen commented on scaffolding-core/src/main/java/net/crystalgames/scaffolding/Scaffolding.java
> +@SuppressWarnings("unused")
Warnings probably shouldn't be suppressed. Unused is a valid thing to supress but I prefer keeping warnings in.

2022-05-18 19:06 UTC, LooFifteen commented on scaffolding-core/src/main/java/net/crystalgames/scaffolding/region/Region.java
> +@SuppressWarnings("unused")
Same suppressing thing here.

2022-05-18 19:06 UTC, SLLCoding commented on scaffolding-editor/build.gradle.kts
> +    implementation("me.alexpanov:free-port-finder:1.1.1")
Should also probably use 25565

2022-05-18 19:33 UTC, DamianKocher commented on scaffolding-core/src/main/java/net/crystalgames/scaffolding/Scaffolding.java
> +@SuppressWarnings("unused")
You're right. If I ever get around to adding proper unit tests suppressing unused warnings won't be necessary. I'll remove them.

2022-05-19 15:49 UTC, SLLCoding commented
Should the server have Moulberry's WorldEdit installed by default instead of recreating a selection tool? It should allow the end user to have more editing capability.

2022-05-19 17:13 UTC, DamianKocher commented
I thought about that. I'm a bit torn on the issue. One one hand, leveraging the 10+ years of development that WE has is a smart move. On the other, I think with enough work it would be possible to surpass the capabilities of what WE has to offer.

I personally would like to go down the second route, but if you want me to cut the editor in favor of using WE I understand.

2022-05-19 17:20 UTC, SLLCoding commented
If you have the time and dedication to do that, go ahead. I'm unable to spend that time unfortunately.

2022-06-11 13:10 UTC, joshuasing commented
Hey @DamianKocher, I am able to work on this in my free time,

2022-06-12 07:31 UTC, closed without merging